blueapp/analis/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('get-post/', views.getPost, name='get-post'),
    path('borrar_sitio_web/<int:sitio_web_id>/', views.borrar_sitio_web, name='borrar_sitio_web'),
    path('agregar_sitio_web/', views.agregar_sitio_web, name='agregar_sitio_web'),
    path('actualizar_sitio_web/<int:sitio_web_id>/', views.actualizar_sitio_web, name='actualizar_sitio_web'),
    path('get_publication_details/', views.get_publication_details, name='get_publication_details'),
    path('new_ai_post/', views.generate_ia_post, name="new_ai_post"),
    path('ai_post/', views.ai_post, name='ai_post'),
]

blueapp/blueapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analis.urls'))
]

blueapp/analis/models.py
from django.db import models

class SitioWeb(models.Model):
    sitio_web_id = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    feed_url = models.CharField(max_length=255)

class Publicacion(models.Model):
    publicacion_id = models.IntegerField(primary_key=True)
    sitio_web = models.ForeignKey(SitioWeb, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    url = models.CharField(max_length=255)
    imagen_portada = models.CharField(max_length=255)
    extracto = models.CharField(max_length=250)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

class Engagement(models.Model):
    engagement_id = models.IntegerField(primary_key=True)
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE)
    reacciones = models.IntegerField()
    comentarios = models.IntegerField()
    veces_compartidas = models.IntegerField()
    comentarios_sitios_web = models.IntegerField()
    total_engagement = models.IntegerField()

class ArticuloGenerado(models.Model):
    articulo_id = models.IntegerField(primary_key=True)
    publicacion = models.OneToOneField(Publicacion, on_delete=models.CASCADE, null=True, blank=True)
    contenido_generado = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=255, default='')
    nombre_sitio_web = models.CharField(max_length=255, default='')
    url_sitio_web = models.CharField(max_length=255, default='')
    post_url = models.CharField(max_length=255, default='')

blueapp/analis/utils/forms.py
from django import forms
from analis.models import SitioWeb

class SitioWebChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.nombre
    
class DateFilterForm(forms.Form):
    start_date = forms.DateField(label='Fecha de inicio', required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(label='Fecha de fin', required=False, widget=forms.DateInput(attrs={'type': 'date'}))
    sitios_web = SitioWebChoiceField(queryset=SitioWeb.objects.all(), required=False, label='Sitios web')

blueapp/analis/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
import json
from .models import SitioWeb, Publicacion, Engagement, ArticuloGenerado
from django.db.models import Sum
from .utils.publications import ultimas_publicaciones
from .utils.new_ai_post import new_ai_post
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator
from django.db.models.functions import TruncDate
from .utils.forms import DateFilterForm 
from datetime import timedelta
from django.views.decorators.http import require_POST
from bs4 import BeautifulSoup


# Vista página de inicio (Index) 
def index(request):
    sitios_web = SitioWeb.objects.all()

    publicaciones = Publicacion.objects.annotate(
        fecha_truncada=TruncDate('fecha_creacion')
    ).order_by('-fecha_truncada', '-engagement__total_engagement')

    # Procesar el formulario de filtro de fechas y sitios web
    date_filter_form = DateFilterForm(request.GET)
    if date_filter_form.is_valid():
        start_date = date_filter_form.cleaned_data['start_date']
        end_date = date_filter_form.cleaned_data['end_date']
        sitios_web_selected = date_filter_form.cleaned_data['sitios_web']

        if start_date:
            publicaciones = publicaciones.filter(fecha_creacion__gte=start_date)
        if end_date:
            # Incluir publicaciones hasta el final del día
            end_date_next_day = end_date + timedelta(days=1)
            publicaciones = publicaciones.filter(fecha_creacion__lte=end_date_next_day)

        if sitios_web_selected:
            publicaciones = publicaciones.filter(sitio_web__in=sitios_web_selected)

        if start_date and end_date:
            # Después del filtro, ordena por engagement de forma descendente
            publicaciones = publicaciones.order_by('-engagement__total_engagement')

    # Obtener las variables de fecha del formulario
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    engagement = Engagement.objects.all()

    paginator = Paginator(publicaciones, 25)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)  
    # Calcular la diferencia para cada página
    page_range = page_obj.paginator.page_range
    if page_obj.paginator.num_pages > 5:
        if page_obj.number <= 3:
            page_range = range(1, 7)
        elif page_obj.number >= page_obj.paginator.num_pages - 3:
            page_range = range(page_obj.paginator.num_pages - 4, page_obj.paginator.num_pages + 1)
        else:
            page_range = range(page_obj.number - 3, page_obj.number + 3)
        
    offset = (page_obj.number - 1) * paginator.per_page  # Calcular el desplazamiento
    num_publicaciones_por_sitio = {}
    for sitio_web in sitios_web:
        publicaciones_sitio = Publicacion.objects.filter(sitio_web=sitio_web)
        num_publicaciones = publicaciones_sitio.count()
        num_publicaciones_por_sitio[sitio_web] = num_publicaciones

    sitios_con_engagement = SitioWeb.objects.annotate(total_engagement=Sum('publicacion__engagement__total_engagement')) 
    # Ordena la lista de sitios por total de engagement de mayor a menor
    sitios_con_engagement = sorted(sitios_con_engagement, key=lambda sitio: sitio.total_engagement or 0, reverse=True)

    # Reemplaza los valores None por cero en la lista de sitios
    for sitio in sitios_con_engagement:
        if sitio.total_engagement is None:
            sitio.total_engagement = 0

    etiquetas = [sitio.nombre for sitio in sitios_con_engagement]
    totales_engagement = [sitio.total_engagement for sitio in sitios_con_engagement]

    context = {
        'sitios_web': sitios_web,
        'publicaciones': publicaciones,
        'num_publicaciones_por_sitio': num_publicaciones_por_sitio,
        'engagement': engagement,
        'page_obj': page_obj,
        'page_range': page_range,
        'offset': offset,
        'sitios_con_engagement': sitios_con_engagement,
        'etiquetas': etiquetas, 
        'totales_engagement': totales_engagement,
        'date_filter_form': date_filter_form,
        'start_date': start_date,  
        'end_date': end_date,  
    }
    return render(request, 'analis/index.html', context)

# Vista para obtener nuevas publicaciones, solo accesible para administradores
@user_passes_test(lambda u: u.is_superuser)
def getPost(request):
    if request.method == 'POST':
        todos_sitios = request.POST.get('todosSitios') == 'on'
        sitios_web_seleccionados = request.POST.getlist('sitiosWeb')
        sitios_web_seleccionados_int = [int(id_str) for id_str in sitios_web_seleccionados if id_str.isdigit()]
        todas_publicaciones = request.POST.get('todasPublicaciones') == 'on'
        number_post_str = request.POST.get('numberPostGet')
        number_post = int(number_post_str) if number_post_str and number_post_str.isdigit() else None

        ultimas_publicaciones(todos_sitios, sitios_web_seleccionados_int, todas_publicaciones, number_post)
    return redirect('/')

# Vista para borrar, solo accesible para administradores
@user_passes_test(lambda u: u.is_superuser)
def borrar_sitio_web(request, sitio_web_id):
    try:
        sitio_web = SitioWeb.objects.get(pk=sitio_web_id)
        sitio_web.delete()
        return JsonResponse({'mensaje': 'Sitio web eliminado correctamente.'})
    except SitioWeb.DoesNotExist:
        return JsonResponse({'error': 'Sitio web no encontrado.'}, status=404)

# Vista para agregar, solo accesible para administradores
@user_passes_test(lambda u: u.is_superuser)
def agregar_sitio_web(request):
    if request.method == 'POST':
        nombre = request.POST.get('sitioNombre')
        url = request.POST.get('sitioUrl')
        feed_url = request.POST.get('sitioRSS')

        # Guardar el sitio web en la base de datos
        sitio_web = SitioWeb(nombre=nombre, url=url, feed_url=feed_url)
        sitio_web.save()

        return redirect('index')  # Cambiar 'nombre_de_tu_vista' al nombre de la vista donde deseas redirigir después de guardar
    return render(request, 'analis/index.html')

# Vista para actualizar, solo accesible para administradores
@user_passes_test(lambda u: u.is_superuser)
def actualizar_sitio_web(request, sitio_web_id):
    sitio_web = get_object_or_404(SitioWeb, pk=sitio_web_id)

    if request.method == 'POST':
        nombre = request.POST.get('actualizarSitioNombre')
        url = request.POST.get('actualizarSitioUrl')
        rss = request.POST.get('actualizarSitioRSS')

        sitio_web.nombre = nombre
        sitio_web.url = url
        sitio_web.feed_url = rss
        sitio_web.save()

        return redirect('index')
    return render(request, 'analis/index.html')

def get_publication_details(request):
    if request.method == 'GET':
        publicacion_id = request.GET.get('publicacion_id')
        try:
            
            publicacion = Publicacion.objects.get(publicacion_id=publicacion_id)
            sitioweb = publicacion.sitio_web
            nombre_sitioweb = sitioweb.nombre
            url_sitioweb = sitioweb.url
            engagement = Engagement.objects.get(publicacion=publicacion)
            
            data = {
                'nombreSitioWeb': nombre_sitioweb,
                'urlSitioWeb': url_sitioweb,
                'titulo': publicacion.titulo,
                'postUrl': publicacion.url,
                'extracto': publicacion.extracto,
                'imagenPortada': publicacion.imagen_portada,
                'engagemet': engagement.total_engagement,
            }
            return JsonResponse(data)
        except (Publicacion.DoesNotExist, Engagement.DoesNotExist):
            return JsonResponse({'error': 'Publicación o engagement no encontrados'})
    return JsonResponse({'error': 'Invalid request'})

@require_POST
# Vista para actualizar, solo accesible para administradores
@user_passes_test(lambda u: u.is_superuser)
def generate_ia_post(request):
    try:
        data = json.loads(request.body.decode('utf-8'))

        titulo_new_post = data.get('titulo', '')
        extracto_html = data.get('extracto', '')
        nombreSitioWeb = data.get('nombreSitioWeb', '')
        urlSitioWeb = data.get('urlSitioWeb', '')
        postUrl = data.get('postUrl', '')

        # Utilizar BeautifulSoup para obtener solo el texto del código HTML
        soup = BeautifulSoup(extracto_html, 'html.parser')
        extracto_texto_new_post = soup.get_text()

        new_ai_post(nombreSitioWeb, urlSitioWeb, postUrl, titulo_new_post, extracto_texto_new_post)

        return JsonResponse({'message': 'Datos recibidos con éxito'})
    except json.JSONDecodeError as e:
        return JsonResponse({'error': 'Error en la decodificación JSON'}, status=400)
    
def ai_post(request):
    posts_generados = ArticuloGenerado.objects.all().order_by('-fecha_creacion')

    # Renderizar la plantilla 'post_ai.html' y enviar los posts generados como contexto
    return render(request, 'analis/post_ai.html', {'posts_generados': posts_generados})    

blueapp/analis/templates/analis/components/header.html
<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'analis/styles.css' %}">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>Blue - Tendencias en Tecnología</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;600&family=Noto+Serif:wght@200&display=swap" rel="stylesheet">

blueapp/analis/templates/analis/components/nav.html
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Blue</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Sitios Web
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#sitiosModal">Listar</a></li>
                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#addSitioModal">Agregar</a></li>
                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#actualizarSitioModal">Actualizar</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#getPostModal">Publicaciones</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Reportes</a>
            </li>
          </ul>
          <span class="navbar-text">
            {% if user.is_authenticated %}
              {% if user.first_name and user.last_name %}
                  <p>Bienvenido, {{ user.first_name }} {{ user.last_name }} </p>
              {% else %}
                  <p>Bienvenido</p>
              {% endif %}
            {% endif %}
          </span>
        </div>
      </div>
  </nav>
</div>    

blueapp/analis/templates/analis/components/posts.html
<div class="container"> 
    <div class="container">
      <br>
      <div class="row">
        <div>
          <form method="get" action="">
            <!-- date_filter_form.html -->

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="{{ date_filter_form.start_date.id_for_label }}">Fecha de inicio:</label>
                    {{ date_filter_form.start_date }}
                </div>
                <div class="form-group col-md-6">
                    <label for="{{ date_filter_form.end_date.id_for_label }}">Fecha de fin:</label>
                    {{ date_filter_form.end_date }}
                </div>
            </div>

            <div class="form-group">
              <label for="{{ date_filter_form.sitios_web.id_for_label }}">Sitios web:</label>
              {{ date_filter_form.sitios_web }}
            </div>

            <button type="submit" class="btn btn-primary">Filtrar</button>
        </form>            
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col"></th>
                <th scope="col">Publicaciones <i>(Tola: {{ publicaciones|length }})</i></th>
              </tr>
            </thead>
            <tbody>
              {% for publicacion in page_obj %}
                <tr data-bs-toggle="modal" data-bs-target="#vistaPreviaModal" data-publicacion-id="{{ publicacion.publicacion_id }}" style="cursor: pointer;">
                  <th class="number-post" scope="row">{{ offset|add:forloop.counter }}</th>
                  <td class="align-middle"><img class="img-post" src="{{publicacion.imagen_portada}}" alt=""></td>
                  <td class="align-middle">
                    <p><b>
                      {% if publicacion.titulo|length > 130 %}
                        {{ publicacion.titulo|slice:":130" }}...
                      {% else %}
                        {{ publicacion.titulo }}
                      {% endif %}
                    </p></b>
                    <p class="infoPost">By {{ publicacion.sitio_web.nombre }} - {{ publicacion.fecha_creacion }} - <span class="engagement">🔥 Engagement: {{ publicacion.engagement_set.first.total_engagement }}</span></p>
                  </td>
                </tr>
              {% endfor%}              
            </tbody>
          </table>
          <nav aria-label="Page navigation example" style="font-size: .8rem;">
            <ul class="pagination">
              <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?page=1{% endif %}{% if start_date %}&start_date={{ start_date }}{% endif %}{% if end_date %}&end_date={{ end_date }}{% endif %}" aria-label="First">
                  <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
              </li>
              <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}{% if start_date %}&start_date={{ start_date }}{% endif %}{% if end_date %}&end_date={{ end_date }}{% endif %}" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              {% for page in page_range %}
                <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                  <a class="page-link" href="?page={{ page }}{% if start_date %}&start_date={{ start_date }}{% endif %}{% if end_date %}&end_date={{ end_date }}{% endif %}">{{ page }}</a>
                </li>
              {% endfor %}
              <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}{% if start_date %}&start_date={{ start_date }}{% endif %}{% if end_date %}&end_date={{ end_date }}{% endif %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
              <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if start_date %}&start_date={{ start_date }}{% endif %}{% if end_date %}&end_date={{ end_date }}{% endif %}" aria-label="Last">
                  <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
              </li>
            </ul>
          </nav> 
        </div>
      </div>  
    </div>
</div>